name: Build and Release Go Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Build
      run: |
        go build -o mqtt-desktop-notify

    - name: Create Git tag
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
        git tag -a "$TAG_NAME" -m "Release version"
        git push origin --tags

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: mqtt-desktop-notify

    - name: Upload build as release asset
      uses: actions/upload-artifact@v4
      with:
        name: mqtt-desktop-notify
        path: mqtt-desktop-notify
